import type { Metadata } from "next";
import { Geist_Mono, Red_Hat_Display } from "next/font/google";
import Header from "@/components/Header";
import "./globals.css";

const redHatDisplay = Red_Hat_Display({
  variable: "--font-red-hat-display",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  other: {
    google: "notranslate",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      translate="no"
      className="notranslate"
    >
      <body
        className={`${redHatDisplay.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <div id="page-content" className="pt-20">
          {children}
        </div>
      </body>
    </html>
  );
}
